### ISSUE TITLE
Should I support Python 3.1-3.2?

### ISSUE THREAD

**Issue by BookOwl** [BookOwl/nustack#13]
Python 3.3 has several features that would make Nustack nicer, the main one being able to stop chained exceptions so that users don't get 3 or 4 deep nested tracebacks when they try to lookup a nonexistent variable.

So, should I support Python 3.2, or just 3.3+?

**Comment by BookOwl** [comment]
@Jonathan50 @liam4, what do you guys think?

**Comment by towerofnix** [comment]
Whaaat? We're using python 3.2?

Why aren't we using 3.5, which is the most up-to-date version?

**Comment by jeandrek** [comment]
I use Python 3.5 :package:
Maybe, if you want to increase where it can be used.
Some GNU/Linux distributions may still be using 3.3<.

**Comment by BookOwl** [comment]
I use Python 3.5 too. I just wanted some feedback on if you guys think supporting Python 3.1-3.2 is worth it.

**Comment by towerofnix** [comment]
3.1 June 27th, 2009
3.1.4 June 11th, 2011
3.2 February 20th, 2011
3.2.6 October 12th, 2014
3.3 September 29th, 2012
3.3.6 October 12th, 2014
3.4 March 16th, 2014
3.4.3 February 12th, 2015
3.5 September 13th, 2015
3.5.1 December 6th, 2015
3.6 December 16th, 2016

As you can see 3.3 was released in 2012 which is kind of a long time ago, but 3.5 was only released in September, not that long ago. I'd probably go for 3.4 or 3.5. The question is, when do we think Nustack will be ready for general big project usage? If we doubt it'll be ready for at least a year or two we should probably go with 3.6 :P

**Comment by Icelys** [comment]
Currently, I use Python 3.4. You might want to use that, as it is _probably_ more stable.

**Comment by BookOwl** [comment]
I've decided to support Python 3.2, since then Nustack can run on PyPy3.

**Comment by jeandrek** [comment]
cool
