### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/nustack#6]
```
>>> -4 show
--ERROR--
NotDefinedError - -4 is not defined in module builtins!
>>> 0 4 - show
-4
```

Negative numbers can be created with `0 x - show` but perhaps the general `-x` syntax should be implemented.

**Comment by BookOwl** [comment]
Will do.

**Comment by BookOwl** [comment]
Added by fff9f5932af9df270ec7f2a09cc6f1cace3f6df0

**Comment by towerofnix** [comment]
Yay!
