### ISSUE TITLE
Less than, greater than

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/nustack#7]
```
>>> 3 6 lt
(NotDefinedError)
>>> 3 6 <
(NotDefinedError)
>>> 3 6 gt
(NotDefinedError)
>>> 3 6 >
(NotDefinedError)
```

We already have `eq`/`=`, so why not the other two main comparison operators?

**Comment by BookOwl** [comment]
Because I forgot. :P
I'll add them.

**Comment by BookOwl** [comment]
Added in 41e5ba0ae85d672ca03a4e629f5f0e2216b03416
