### ISSUE TITLE
No module named 'nustack.stdlib.Turtle'

### ISSUE THREAD

**Issue by jeandrek** [BookOwl/nustack#9]
The turtle_tree.nu example at nustack/examples/turtle_tree.nu doesn't work.
I get this error:

```
--ERROR--
ImportError - No module named 'nustack.stdlib.Turtle'
Raise error? (y/n) n
```

**Comment by jeandrek** [comment]
Wait no I didn't have the latest version. The old `git clone` method is now broken but I see you fixed PyPi. It works great! :smiley:

**Comment by BookOwl** [comment]
Thanks! :smiley:

**Comment by jeandrek** [comment]
Wow lol I was just playing around with Nustack and then the comment popped up xD
